In [1]:
import numpy as np


In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.zeros(2)

array([0., 0.])

In [4]:
np.ones(2)

array([1., 1.])

In [5]:
np.empty(2)

array([1., 1.])

In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

`numpy.linspace` is a function in Python's NumPy library that generates a sequence of evenly spaced values within a defined interval. It's often used in numerical computations.

Here's a simple example:



In [ ]:
import numpy as np

# Generate 5 numbers between 1 and 10, evenly spaced.
numbers = np.linspace(1, 10, 5)

print(numbers)



In this example, `np.linspace(1, 10, 5)` generates 5 numbers between 1 and 10 (inclusive) that are evenly spaced. The output will be:



In [ ]:
[ 1.    3.25  5.5   7.75 10.  ]



So, the numbers 1, 3.25, 5.5, 7.75, and 10 are evenly spaced across the range from 1 to 10.

`np.newaxis` is used to increase the dimension of the existing array by one more dimension. It's a convenient alias for `None`, and useful in scenarios where you need to add an extra dimension to your array.

Here's a simple example:



In [ ]:
import numpy as np

# Create a 1D array
a = np.array([1, 2, 3, 4, 5])

# Use np.newaxis to add a new dimension
b = a[np.newaxis, :]

print("Original array shape:", a.shape)
print("New array shape:", b.shape)



In this example, `a` is a 1-dimensional array. When we use `a[np.newaxis, :]`, we add an extra dimension, turning it into a 2-dimensional array. The output of the shapes will be:



In [ ]:
Original array shape: (5,)
New array shape: (1, 5)



So, the original array had 5 elements in one dimension, and the new array has 5 elements in one dimension but within another dimension.

In [3]:
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
identity.shape

(3, 3)

In [5]:
identity.dtype

dtype('float64')

In [6]:
len(identity)

3

In [7]:
identity.size

9

In [8]:
identity.ndim

2

In [11]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [14]:
b=np.arange(1,5)
b

array([1, 2, 3, 4])

In [17]:
h=a+b
h
np.add(a,b)
i=a-b
i
np.subtract(a,b)


array([0, 0, 0, 0])

In [20]:
arr=np.array([7,2,6,4,1])


In [21]:
np.sort(arr)

array([1, 2, 4, 6, 7])

In [22]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [23]:
# concatenate these arrays
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
x = np.array([[1, 2], [3, 4]]) # 2x2 array
y = np.array([[5, 6]]) # 1x2 array

In [25]:
w = np.array([[5,1], [7,1]]) # 2x2 array
x = np.array([[1, 2], [3, 4]]) # 2x2 array

In [26]:
z1 = np.concatenate((w,x), axis=1)
z1

array([[5, 1, 1, 2],
       [7, 1, 3, 4]])

In [27]:
# create a 3D array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [28]:
array_example.size

24

In [29]:
# creata 3D array of size (3,1,4)
a1 = np.array([[[0, 1, 2, 3]],
                          [[4, 5, 6, 7]],
                          [[0, 1, 2, 3]]])
a1.shape

(3, 1, 4)

In [30]:
# reshape the a 
a2 = a1.reshape(6,2)
a2.shape

(6, 2)

In [31]:
# create a 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [32]:
# convert that into 2D array
b = a[np.newaxis, :]
b.shape
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [33]:
c = a[: , np.newaxis]
c.shape
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [34]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
a[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [36]:
b = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
b[b <= 10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
b[b % 2 == 0] # filter even numbers

array([ 2,  4,  6,  8, 10, 12])

In [39]:
# filter odd numbers
b[b % 2 == 1] 

array([ 1,  3,  5,  7,  9, 11])

In [40]:
# use two conditions
b[(b > 2) & (b < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
# use three conditions and filter the arrays
b[(b > 2) & (b < 11) & (b % 2 == 0)]

array([ 4,  6,  8, 10])

In [42]:
b[(b > 2) | (b < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])